trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'  # Corrected pool value

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- checkout: self  # Checkout the repository linked to the pipeline

# Checkout an additional repository
- checkout: 
    repository:'https://dev.azure.com/ganeshraja0243/ganesh-test-2/_git/ganesh-docker'
    persistCredentials:true  # Optional, but ensures credentials persist for further operations

- task: Docker@2
  displayName: 'Build an image'
  inputs:
    repository: $(imageName)
    dockerfile: '**/Dockerfile'  # Looks for Dockerfile in any subdirectory
    command: build
