resources:
  repositories:
  - repository: 'MYGITHUB'
    type: github
    endpoint: https://github.com/Ganeshraja1992/ganesh-docker
    name: Ganeshraja1992/ganesh-docker

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'  # Corrected pool value

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- checkout: self  # Checkout the repository linked to the pipeline

- task: Docker@2
  displayName: 'Build an image'
  inputs:
    repository: $(imageName)
    dockerfile: '**/Dockerfile'  # Looks for Dockerfile in any subdirectory
    command: build
