trigger:
  - main

pool: 'ubuntu'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- checkout: self

- task: Docker@2
  displayName: 'Build an image'
  inputs:
    repository: $(imageName)
    dockerfile: '**/Dockerfile'  # Looks for Dockerfile in any subdirectory
    command: build
