trigger:
  - main

pool: 'ubuntu'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- checkout: self  # Ensures the latest code is checked out

- task: Docker@2
  displayName: 'Build an image'
  inputs:
    repository: $(imageName)
    dockerfile: '/root/dockerfiles'  # Looks for Dockerfile in any subdirectory
    command: build